[tool.poetry]
version = "0.1.0"
requires-poetry = '>=2.0'

packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
requests = "^2.31.0"
ujson = "^5.8.0"
pynacl = "1.5.0"
yt-dlp = "2025.1.15"
async-lru = "^2.0.4"
async-timeout = "^5.0.1"
discord-py = {git = "https://github.com/Rapptz/discord.py.git", rev = "master"}

[project]
name = "discord-music-bot"
description = ""
dynamic = ["version", "dependencies"]
readme = "README.md"
authors = []
maintainers = []
requires-python = '>=3.11,<4.0'
